# name: Release CI

# on:
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# jobs:
#   create-release:
#     runs-on: ubuntu-20.04
#     outputs:
#       RELEASE_UPLOAD_ID: ${{ steps.create_release.outputs.id }}

#     steps:
#       - uses: actions/checkout@v2
#       - name: Query version number
#         id: get_version
#         shell: bash
#         run: |
#           echo "using version tag ${GITHUB_REF:10}"
#           echo "version=${GITHUB_REF:10}" >> $GITHUB_ENV

#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: '${{ env.version }}'
#           release_name: 'ChatGPT ${{ env.version }}'
#           body: 'See the assets to download this version and install.'

#   build-tauri:
#     needs: create-release
#     strategy:
#       fail-fast: false
#       matrix:
#         platform: [macos-latest, ubuntu-20.04, windows-latest]

#     runs-on: ${{ matrix.platform }}
#     steps:
#       - uses: actions/checkout@v3
#       - name: setup node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16

#       - name: install Rust stable
#         uses: dtolnay/rust-toolchain@stable
#       - name: install dependencies (ubuntu only)
#         if: matrix.platform == 'ubuntu-20.04'
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

#       - name: Install app dependencies and build it
#         run: yarn && yarn build:fe

#       - name: fix tray icon
#         if: matrix.platform != 'macos-latest'
#         run: |
#           yarn fix:tray

#       - uses: tauri-apps/tauri-action@v0.3
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           # üìù: https://tauri.app/v1/guides/distribution/updater#signing-updates
#           TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
#           TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
#         with:
#           releaseId: ${{ needs.create-release.outputs.RELEASE_UPLOAD_ID }}

#   updater:
#     runs-on: ubuntu-20.04
#     needs: [create-release, build-tauri]

#     steps:
#       - uses: actions/checkout@v2
#       - run: yarn
#       - run: yarn updater --token=${{ secrets.GITHUB_TOKEN }}

#       - name: Deploy install.json
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # üìù: Edit the deployment directory
#           publish_dir: ./updater
#           force_orphan: true
